
name: Deploy Vite App

on:
  push:
    branches:
      - main  # Runs deployment when code is pushed to "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_BASE_URL: "/EvolveX_club/" # Pass the base URL during build

      - name: Copy 404.html to dist folder
        run: cp public/404.html dist/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true # Automatically remove deleted files from the deploy branch
